package com.example.demo.entities;
// Generated May 23, 2018 1:38:46 AM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Taikhoan generated by hbm2java
 */
@Entity
@Table(name = "taikhoan", catalog = "shophandmade", uniqueConstraints = @UniqueConstraint(columnNames = "TEN_DANGNHAP"))
public class Taikhoan implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idTk;
	private String tenDangnhap;
	private String matKhau;
	private String chucvu;
	private String tenKh;
	private String diachi;
	private String sdt;
	private Integer isConfirm;

	public Taikhoan() {
	}

	public Taikhoan(String tenDangnhap, String matKhau) {
		this.tenDangnhap = tenDangnhap;
		this.matKhau = matKhau;
	}
	
	public Taikhoan(String tenDangnhap, String matKhau, String tenKh, String diachi, String sdt) {
		super();
		this.tenDangnhap = tenDangnhap;
		this.matKhau = matKhau;
		this.chucvu = "KH";
		this.tenKh = tenKh;
		this.diachi = diachi;
		this.sdt = sdt;
		this.isConfirm = 1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_TK", unique = true, nullable = false)
	public Integer getIdTk() {
		return this.idTk;
	}

	public void setIdTk(Integer idTk) {
		this.idTk = idTk;
	}

	@Column(name = "TEN_DANGNHAP", unique = true, nullable = false, length = 200)
	public String getTenDangnhap() {
		return this.tenDangnhap;
	}

	public void setTenDangnhap(String tenDangnhap) {
		this.tenDangnhap = tenDangnhap;
	}

	@Column(name = "MAT_KHAU", nullable = false, length = 200)
	public String getMatKhau() {
		return this.matKhau;
	}

	public void setMatKhau(String matKhau) {
		this.matKhau = matKhau;
	}

	@Column(name = "CHUCVU", length = 50)
	public String getChucvu() {
		return this.chucvu;
	}

	public void setChucvu(String chucvu) {
		this.chucvu = chucvu;
	}

	@Column(name = "TEN_KH", length = 200)
	public String getTenKh() {
		return this.tenKh;
	}

	public void setTenKh(String tenKh) {
		this.tenKh = tenKh;
	}

	@Column(name = "DIACHI", length = 200)
	public String getDiachi() {
		return this.diachi;
	}

	public void setDiachi(String diachi) {
		this.diachi = diachi;
	}

	@Column(name = "SDT", length = 15)
	public String getSdt() {
		return this.sdt;
	}

	public void setSdt(String sdt) {
		this.sdt = sdt;
	}

	@Column(name = "IS_CONFIRM")
	public Integer getIsConfirm() {
		return this.isConfirm;
	}

	public void setIsConfirm(Integer isConfirm) {
		this.isConfirm = isConfirm;
	}

}
