package com.example.demo.entities;
// Generated May 2, 2018 12:43:54 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Taikhoan generated by hbm2java
 */
@Entity
@Table(name = "taikhoan", catalog = "shophandmade")
public class Taikhoan implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idTk;
	private String tenDangnhap;
	private String matKhau;
	private String chucvu;
	private String tenKh;
	private String diachi;
	private String sdt;
	private Integer isConfirm;

	public Taikhoan() {
	}
	
	public Taikhoan(String tenDangnhap, String matKhau) {
		this.tenDangnhap = tenDangnhap;
		this.matKhau = matKhau;
	}

	public Taikhoan(String tenDangnhap, String matKhau, String chucvu, String tenKh, String diachi, String sdt,
			Integer isConfirm) {
		this.tenDangnhap = tenDangnhap;
		this.matKhau = matKhau;
		this.chucvu = chucvu;
		this.tenKh = tenKh;
		this.diachi = diachi;
		this.sdt = sdt;
		this.isConfirm = isConfirm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_TK", unique = true, nullable = false)
	public Integer getIdTk() {
		return this.idTk;
	}

	public void setIdTk(Integer idTk) {
		this.idTk = idTk;
	}

	@Column(name = "TEN_DANGNHAP", length = 200)
	public String getTenDangnhap() {
		return this.tenDangnhap;
	}

	public void setTenDangnhap(String tenDangnhap) {
		this.tenDangnhap = tenDangnhap;
	}

	@Column(name = "MAT_KHAU", length = 200)
	public String getMatKhau() {
		return this.matKhau;
	}

	public void setMatKhau(String matKhau) {
		this.matKhau = matKhau;
	}

	@Column(name = "CHUCVU", length = 50)
	public String getChucvu() {
		return this.chucvu;
	}

	public void setChucvu(String chucvu) {
		this.chucvu = chucvu;
	}

	@Column(name = "TEN_KH", length = 200)
	public String getTenKh() {
		return this.tenKh;
	}

	public void setTenKh(String tenKh) {
		this.tenKh = tenKh;
	}

	@Column(name = "DIACHI", length = 200)
	public String getDiachi() {
		return this.diachi;
	}

	public void setDiachi(String diachi) {
		this.diachi = diachi;
	}

	@Column(name = "SDT", length = 15)
	public String getSdt() {
		return this.sdt;
	}

	public void setSdt(String sdt) {
		this.sdt = sdt;
	}

	@Column(name = "IS_CONFIRM")
	public Integer getIsConfirm() {
		return this.isConfirm;
	}

	public void setIsConfirm(Integer isConfirm) {
		this.isConfirm = isConfirm;
	}

}
